ALTER TABLE daily_stats ADD COLUMN IF NOT EXISTS theta_pnl FLOAT DEFAULT 0.0;
ALTER TABLE daily_stats ADD COLUMN IF NOT EXISTS vega_pnl FLOAT DEFAULT 0.0;
ALTER TABLE daily_stats ADD COLUMN IF NOT EXISTS broker_pnl FLOAT DEFAULT 0.0;
ALTER TABLE daily_stats ADD COLUMN IF NOT EXISTS pnl_discrepancy FLOAT DEFAULT 0.0;
ALTER TABLE daily_stats ADD COLUMN IF NOT EXISTS circuit_breaker_triggered BOOLEAN DEFAULT FALSE;
